# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PapersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abstract', models.TextField()),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='keywords',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.PapersList'),
        ),
        migrations.AddField(
            model_name='authors',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.PapersList'),
        ),
    ]
