# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20160625_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='author',
        ),
    ]
