# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20160625_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperlist',
            old_name='name',
            new_name='title',
        ),
    ]
