# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_paperlist_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlist',
            name='location',
            field=models.TextField(default='1.pdf'),
            preserve_default=False,
        ),
    ]
