# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_paperlist_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='keywords',
            name='paper',
        ),
        migrations.RenameField(
            model_name='paperlist',
            old_name='location',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='paperlist',
            name='accepted',
        ),
        migrations.DeleteModel(
            name='author',
        ),
        migrations.DeleteModel(
            name='keywords',
        ),
    ]
