# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_auto_20160626_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlist',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
