# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20160626_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlist',
            name='accepted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperlist',
            name='file',
            field=models.FileField(upload_to='files/projects_all/%Y/%m/%d'),
        ),
    ]
